config/routes.rb
BaseApp::Application.routes.draw do

  resources :messagers

  root :to => "pages#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
  										:registrations => "registrations" }


  get "pages/index"

  get "/admin" => "admin/base#index", :as => "admin"

  namespace "admin" do

    resources :users

  end

  resources :tourneys
  resources :tourney_comments

  match 'users/dashboard', :to => 'user#index', :via => [:get], :as => :my_dashboard
  match 'users/:id', :to => 'user#members_dashboard', :via => [:get], :as => :users_dashboard

  match '/tourneys/:id/rsvp', :to => 'tourneys#rsvp', :via => [:post], :as => :tourneys_rsvp
end

app/models/board.rb
class Board < ActiveRecord::Base
end

app/models/cards.rb
class Cards < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :game_type
end

app/models/game_mode.rb
class GameMode < ActiveRecord::Base
end

app/models/game_type.rb
class GameType < ActiveRecord::Base
end

app/models/games.rb
class Games < ActiveRecord::Base
  belongs_to :game_type
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  belongs_to :tourney
end

app/models/join_tourney.rb
class JoinTourney < ActiveRecord::Base
  belongs_to :user
  belongs_to :tourney
end

app/models/messager.rb
class Messager < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base

  has_and_belongs_to_many :users

  def self.admin
    find_or_create_by(:name => "admin")
  end

end

app/models/rsvp_stats.rb
class RsvpStats < ActiveRecord::Base
  belongs_to :users
  belongs_to :tourneys
end

app/models/schedules.rb
class Schedules < ActiveRecord::Base
end

app/models/sports.rb
class Sports < ActiveRecord::Base
end

app/models/tourney.rb
class Tourney < ActiveRecord::Base
  belongs_to :tourney_type
  belongs_to :tourney_comment
  belongs_to :tourney_comments
  belongs_to :user
  belongs_to :venue
  belongs_to :game_type
end

app/models/tourney_comment.rb
class TourneyComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :tourney
end

app/models/tourney_type.rb
class TourneyType < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable

  has_and_belongs_to_many :roles
  belongs_to :tourney

  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end

  def make_admin
    self.roles << Role.admin
  end

  def revoke_admin
    self.roles.delete(Role.admin)
  end

  def admin?
    role?(:admin)
  end

  attr_accessor :login, :new_user

  def password_salt
    "no salt"
  end

  def password_salt=(salt)
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def new_user=(new_user)
    @new_user = new_user
  end

  def new_user
    @new_user
  end

  # new function to set the password without knowing the current password used in our confirmation controller.
  def attempt_set_password(params)
    update_attributes(params)
  end
  # new function to return whether a password has been set
  def has_no_password?
    self.encrypted_password.blank?
  end

  # new function to provide access to protected method unless_confirmed
  def only_if_unconfirmed
    pending_any_confirmation {yield}
  end

  # Password is required if it is being set, but not for new records
  def password_required?
    if !persisted?
      false
    else
      !password.nil? || !password_confirmation.nil?
    end
  end

  def password_match?
    self.errors[:password] << "can't be blank" if password.blank?
    self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    self.errors[:password_confirmation] << "does not match password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token['info']
    if user = User.find_by_email(data["email"])
      user
    else # Create a user with a stub password.
      User.create!(:email => data["email"], :password => Devise.friendly_token[0,20])
    end
  end

end

app/models/venues.rb
class Venues < ActiveRecord::Base
end

app/models/video_game.rb
class VideoGame < ActiveRecord::Base
end

app/models/video_games.rb
class VideoGames < ActiveRecord::Base
end

app/controllers/tourneys_controller.rb
class TourneysController < ApplicationController
  before_action :set_tourney, only: [:show, :edit, :update, :destroy]

  # GET /tourneys
  def index
    @tourneys = Tourney.all
    @tourney_comment = TourneyComment.new
  end

  # GET /tourneys/1
  def show
  end

  # GET /tourneys/new
  def new
    @tourney = Tourney.new
  end

  # GET /tourneys/1/edit
  def edit
  end

  # POST /tourneys
  def create
    @tourney = Tourney.new(tourney_params)

    if @tourney.save
      redirect_to @tourney, notice: 'Tourney was successfully created.'
    else
      render :new
    end
  end



  # PATCH/PUT /tourneys/1
  def update
    if @tourney.update(tourney_params)
      redirect_to @tourney, notice: 'Tourney was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tourneys/1
  def destroy
    @tourney.destroy
    redirect_to tourneys_url, notice: 'Tourney was successfully destroyed.'
  end


  def rsvp
    @user_id = params[:user_id]
    JoinTourney.create([
          {:user_id => current_user.id, 
            :tourney_id => params[:tourney_id] },
            ])
    @user_details =  User.find(@user_id)
    respond_to do |format|
      format.json { render :json => @user_details.to_json }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tourney
      @tourney = Tourney.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tourney_params
      params.require(:tourney).permit(:title, :desc, :start_date, :end_date, :user_id, :venue_id, :game_type_id, :tourney_type_id, :game_id)
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tourneys_helper.rb
module TourneysHelper
	def user_tourneys
		JoinTourney.where(:tourney_id=>params[:id])
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/tourneys/_form.html.erb
<%= form_for(@tourney, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @tourney.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tourney.errors.count, "error") %> prohibited this tourney from being saved:</h2>

      <ul>
      <% @tourney.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => "col-sm-3 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :title, :class => "form-control", :placeholder => "Amaze them with your Tourney Subject!" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :desc, :class => "col-sm-3 control-label" %>
    <div class="col-sm-4">
      <%= f.text_area :desc, :class => "form-control", :placeholder => "Amaze them even more!" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :tourney_type_id, :class => "col-sm-3 control-label" %>
    <div class="col-sm-4">
      <%= f.collection_select :tourney_type_id, TourneyType.all, :id, :tourney_name, {:include_blank => false}, :class => "form-control" %>
    <%= f.hidden_field :user_id,:value=> current_user.id %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :start_date, :class => "col-sm-3 control-label" %>
    <div class="col-sm-5">
      <%= f.datetime_select :start_date, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :end_date, :class => "col-sm-3 control-label" %>
    <div class="col-sm-5">
      <%= f.datetime_select :end_date, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :venue_id, :class => "col-sm-3 control-label" %>
    <div class="col-sm-4">
      <%= f.text_area :venue_id, :class => "form-control", :placeholder => "" %>
    </div>
  </div>


  <div class="form-group">
    <%= f.label :game_type_id, :class => "col-sm-3 control-label" %>
    <div class="col-md-4">
      <%= f.select :game_type_id, GameType.all.map{ |c| [c.name, "#{c.id}"] } %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :game_id, :class => "col-sm-3 control-label" %>
    <div class="col-md-4">
      <%= f.select :game_id, Game.all.map{ |c| [c.name, "#{c.id}",{'game-type-id'=>c.game_type_id}] } %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4">
      <%= f.submit "Submit" ,:class => "btn btn-default" %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $(function(){
    $('#tourney_game_type_id').on('change', function(e){
      console.log('change');
      $('#tourney_game_id option').show();
      var iVal = $(this).val();
      var uiGameSelect = $('#tourney_game_id').val();
      if(typeof(uiGameSelect) !='undefined'){
        $('#tourney_game_id option[game-type-id !="'+iVal+'"]').hide()
      }
    });
    $('#tourney_game_type_id').trigger('change'); 
  });
</script>

app/views/tourneys/edit.html.erb
<h1>Editing tourney</h1>

<%= render 'form' %>

<%= link_to 'Show', @tourney %> |
<%= link_to 'Back', tourneys_path %>

app/views/tourneys/index.html.erb
<section id="hottest-tourney" class="no-padding">
  <div class="wrapper">
    <div class="container">
    <h1>Featured Tourneys</h1>
      <div class="row tourney-list-tournaments">
        <div class="row">
            <div class="col-md-3">
                by: Dwyane Wade<br/>
                3 months ago
            </div>
            <div class="col-md-6">
              <h4><b>Friday Night Magic</b></h4>
            </div>
            <div class="col-md-3" align='left'>
              Tournament<br />
              Location Here
            </div>
          </div>
        </div>
      <div class="row tourney-list-casuals">
        <div class="row">
            <div class="col-md-3">
                by: Bogart Porto<br/>
                3 months ago
            </div>
            <div class="col-md-6">
              <h4><b>1v1 basketball</b></h4>
            </div>
            <div class="col-md-3" align='left'>
              Casuals<br />
              Location Here
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="wrapper">
  <div class="container">
    <br />
     <%= link_to 'Organize a Tourney!', new_tourney_path, :class => "btn btn-default" %>
    <% @tourneys.each do |tourney| %>
        <%if tourney.tourney_type_id == 2%>
          <div class="row tourney-list-casuals">
        <%else%>
          <div class="row tourney-list-tournaments">
        <%end%>
          <div class="row">
            <div class="col-md-3">
                by: <a href="<%= users_dashboard_path(tourney.user.id)%>"><%= tourney.user.first_name %> <%= tourney.user.last_name %></a><br/>
                <%= time_ago_in_words(tourney.start_date).gsub('about','') + ' ago' %>
            </div>
            <div class="col-md-6">
              <h4><b><%= link_to tourney.title, tourney_path(tourney.id) %></b></h4>
            </div>
            <div class="col-md-3" align='left'>
              <%= tourney.tourney_type.tourney_name%><br>
              Location Here
            </div>
          </div>
        </div>
    <%end%>
  </div>
</div>

app/views/tourneys/new.html.erb
<style type="text/css">
	select{
		color: #000;
	}
</style>
<section id="hottest-tourney" class="no-padding">
	<div class="wrapper">
	    <div class="container">
	      <div class="page-header">
	        <h2>Add a new Tourney</h2>
	      </div>

			<%= render 'form' %>
		</div>
	</div>
</section>

app/views/tourneys/show.html.erb
<section class="highlight-view">

  <div class="wrapper">

    <div class="row">
      <div class="col-sm-2">
        <div>
          <%= image_tag('SMMGrandFinalLogo.png' , :width => "150px") %>
        </div>

        <div>
          <%= link_to 'Edit', edit_tourney_path(@tourney) %> |
          <%= link_to 'Back', tourneys_path %>
        </div>
      </div>
      <div class="col-sm-5">
        <p id="notice"><%= notice %></p>
          <h1>
            <%= @tourney.title %>
          </h1>


        <%= @tourney.desc %>


        <p>
          <strong>Tourney type:</strong>
          <%= @tourney.tourney_type.tourney_name %>
        </p>

        <p>

          <strong>Start date:</strong>
          <%= @tourney.start_date.strftime("%B %d, %Y") %>

        </p>

        <p>
          <strong>End date:</strong>
          <%= @tourney.end_date.strftime("%B %d, %Y") %>
        </p>

        <p>
          <strong>User:</strong>
          <%= @tourney.user.first_name %> <%# @tourney.user.last_name %>
        </p>

        <p>
          <strong>Venue:</strong>
          <%# @tourney.venue %>
        </p>

        <p>
          <strong>Game type:</strong>
          <%= @tourney.game_type.name %>
        </p>

        <p>
          <strong>RSVP:</strong>
          <%# @tourney.rsvp_stats.status%>
        </p>

        <p>
          <button class="btn-success rvsp_btn" type="going">Going</button>
          <button class="btn-success rvsp_btn" type="maybe">Maybe</button>
          <button class="btn-success rvsp_btn" type="not">Not Going</button>

        </p>
      </div>
      <div class="col-sm-5">
      <br>
        <h3>Participants</h3>
        <ul>
          <% user_tourneys.each do |list| %>
            <li align="left">
              <%= list.user.first_name%> <%= list.user.last_name%> 
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</section>


<div class="wrapper">

  <div id="comment_box">
  </div>
    <div id="comment_reply_box">

      <div class="row comment">
        <div class="col-sm-2" style="margin-top: 0px;">
          <%= image_tag('sample.png' ,:width=> '100px') %>
        </div>

        <div class="col-sm-10">
          <h2>Meng David</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam in justo et purus dignissim adipiscing ac vel erat. Aenean consectetur massa nunc, ac eleifend libero vehicula consectetur. Praesent at commodo quam. Curabitur vulputate pretium mauris, vitae sagittis neque varius vitae.
          </p>
        </div>
      </div>
    </div>

      <div class="row comment">
        <div class="col-sm-2" style="margin-top: 0px;">
          <%= image_tag('sample.png' ,:width=> '100px') %>
        </div>

        <div class="col-sm-10">
          <h2>Meng David</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam in justo et purus dignissim adipiscing ac vel erat. Aenean consectetur massa nunc, ac eleifend libero vehicula consectetur. Praesent at commodo quam. Curabitur vulputate pretium mauris, vitae sagittis neque varius vitae.
          </p>
        </div>
      </div>

      <div class="row comment">
        <div class="col-sm-2" style="margin-top: 0px;">
          <%= image_tag('sample.png' ,:width=> '100px') %>
        </div>

        <div class="col-sm-10">
          <h2>Meng David</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam in justo et purus dignissim adipiscing ac vel erat. Aenean consectetur massa nunc, ac eleifend libero vehicula consectetur. Praesent at commodo quam. Curabitur vulputate pretium mauris, vitae sagittis neque varius vitae.
          </p>
        </div>
      </div>
</div>


<script type="text/javascript">
    $(function(){

      $('.rvsp_btn').click(function(){
        var uiTarget = $(this);
        var sType = uiTarget.attr('type');

        if(typeof(sType) !='undefined'){
          $.ajax({
            type: 'POST',
            data: {
              'user_id' :'<%= current_user.id %>',
              'tourney_id' : '<%= params[:id] %>'
            },
            url: 'tourneys/rsvp',
            success: function(data){
              console.log(JSON.stringify(data));
              var oData = data,
                  sFname = oData.first_name,
                  sLast = oData.last_name,
                  iMobile = oData.contact;
              oData.full_name = sFname +' ' +sLast;
              oData.message = 'Thank you ' + oData.full_name;
              oData.mobile_number = oData.mobile_number;
              send_sms_notif(oData);
            }
          });
        }
      });



      
      function send_sms_notif(data){
        console.log(JSON.stringify(data));
        $.ajax({
          type: 'POST',
          url: 'https://post.chikka.com/smsapi/request',
          data: {
            'client_id' : '20979ad86da809c5aec43d96d18d603b7f75248d7bf57ae67101c972f57c8e02',
            'secret_key' : '698116eb37a7639365f9424b278d91fe4b2bba5781e8aea79785db2b1b095934',
            'shortcode' : '292908769',
            'message_id' : '12345678123456781234567812345678',
            'message' : 'test',
            'message_type' : 'SEND',
            'mobile_number' : '639265422258'
          },
          success : function(){
            window.location.reload()
          }
        });
      }
    }); 
</script>