config/routes.rb
BaseApp::Application.routes.draw do

  resources :messagers

  root :to => "pages#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
  										:registrations => "registrations" }


  get "pages/index"

  get "/admin" => "admin/base#index", :as => "admin"

  namespace "admin" do

    resources :users

  end

  resources :tourneys
  resources :tourney_comments

  match 'users/dashboard', :to => 'user#index', :via => [:get], :as => :my_dashboard
  match 'users/:id', :to => 'user#members_dashboard', :via => [:get], :as => :users_dashboard

  match '/tourneys/:id/rsvp', :to => 'tourneys#rsvp', :via => [:post], :as => :tourneys_rsvp
end

app/models/board.rb
class Board < ActiveRecord::Base
end

app/models/cards.rb
class Cards < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :game_type
end

app/models/game_mode.rb
class GameMode < ActiveRecord::Base
end

app/models/game_type.rb
class GameType < ActiveRecord::Base
end

app/models/games.rb
class Games < ActiveRecord::Base
  belongs_to :game_type
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  belongs_to :tourney
end

app/models/join_tourney.rb
class JoinTourney < ActiveRecord::Base
  belongs_to :user
  belongs_to :tourney
end

app/models/messager.rb
class Messager < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base

  has_and_belongs_to_many :users

  def self.admin
    find_or_create_by(:name => "admin")
  end

end

app/models/rsvp_stats.rb
class RsvpStats < ActiveRecord::Base
  belongs_to :users
  belongs_to :tourneys
end

app/models/schedules.rb
class Schedules < ActiveRecord::Base
end

app/models/sports.rb
class Sports < ActiveRecord::Base
end

app/models/tourney.rb
class Tourney < ActiveRecord::Base
  belongs_to :tourney_type
  belongs_to :tourney_comment
  belongs_to :tourney_comments
  belongs_to :user
  belongs_to :venue
  belongs_to :game_type
end

app/models/tourney_type.rb
class TourneyType < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable

  has_and_belongs_to_many :roles
  belongs_to :tourney

  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end

  def make_admin
    self.roles << Role.admin
  end

  def revoke_admin
    self.roles.delete(Role.admin)
  end

  def admin?
    role?(:admin)
  end

  attr_accessor :login, :new_user

  def password_salt
    "no salt"
  end

  def password_salt=(salt)
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def new_user=(new_user)
    @new_user = new_user
  end

  def new_user
    @new_user
  end

  # new function to set the password without knowing the current password used in our confirmation controller.
  def attempt_set_password(params)
    update_attributes(params)
  end
  # new function to return whether a password has been set
  def has_no_password?
    self.encrypted_password.blank?
  end

  # new function to provide access to protected method unless_confirmed
  def only_if_unconfirmed
    pending_any_confirmation {yield}
  end

  # Password is required if it is being set, but not for new records
  def password_required?
    if !persisted?
      false
    else
      !password.nil? || !password_confirmation.nil?
    end
  end

  def password_match?
    self.errors[:password] << "can't be blank" if password.blank?
    self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    self.errors[:password_confirmation] << "does not match password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token['info']
    if user = User.find_by_email(data["email"])
      user
    else # Create a user with a stub password.
      User.create!(:email => data["email"], :password => Devise.friendly_token[0,20])
    end
  end

end

app/models/venues.rb
class Venues < ActiveRecord::Base
end

app/models/video_game.rb
class VideoGame < ActiveRecord::Base
end

app/models/video_games.rb
class VideoGames < ActiveRecord::Base
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <title>Base Application - Admin Dashboard</title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>

    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>

    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= yield :head %>

  </head>

  <body>

    <%= render "layouts/admin/main_nav" %>

    <div class="container">

    <%= render "layouts/application/flash_messages" %>

      <%= yield %>

    </div>

  </body>

</html>

app/views/layouts/admin/_main_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#baseapp-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Base Application", admin_path, :class => "navbar-brand" %>
    </div>


    <div class="collapse navbar-collapse" id="baseapp-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to("Users", admin_users_path) %></li>
        <li><%= link_to("Exit →", root_path) %></li>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <title>Tourney</title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= favicon_link_tag 'favicon.ico' %>

    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= yield :head %>

  </head>

  <body>
      <%= render "layouts/application/header" %>

      <div class="container-fluid no-padding">

        <%= render "layouts/application/flash_messages" %>

        <%= yield %>

      </div>

      <%= render "layouts/application/footer" %>
  </body>

</html>

app/views/pages/_newest_tourney_casuals.html.erb
<div class="tourn-listing-casuals row">
<div class="col-sm-12 ">
		<span>
			<strong style="float: left;">
				<%= link_to newest_tourney_casuals.title, tourneys_path(newest_tourney_casuals.id) %>
			</strong>
		</span>
	</div>
	<br />
	<div class="col-sm-12 pull-right">
		<small style="float: left;">
			By: <a href="<%= users_dashboard_path(newest_tourney_casuals.user.id) %>">
			<%= newest_tourney_casuals.user.first_name%>
			<%= newest_tourney_casuals.user.last_name%>
			</a>
		</small>
	</div>
	<br />
	<div class="col-md-12">
		<small class="pull-left">
			<%= time_ago_in_words(newest_tourney_casuals.created_at).gsub('about','') + ' ago' %>
		</small>
		<small class="pull-right">
			Los Angeles City
		</small>
	</div>
</div>

app/views/pages/_newest_tourney_tournaments.html.erb
<div class="tourn-listing-tournaments row">
<div class="col-sm-12">
		<span>
			<strong style="float: left;">
				<%= link_to newest_tourney_tournaments.title, tourney_path(newest_tourney_tournaments.id) %>
			</strong>
		</span>
	</div>
	<div class="col-sm-12 pull-right">
		<small style="float: left;">
			By: <a class="person" href="<%= users_dashboard_path(newest_tourney_tournaments.user.id) %>"><%= newest_tourney_tournaments.user.first_name%> <%= newest_tourney_tournaments.user.last_name%></a>
		</small>
	</div>
	<br />
	<div class="col-md-12">
		<small class="pull-left">
			<%= time_ago_in_words(newest_tourney_tournaments.created_at).gsub('about','') + ' ago' %>
		</small>
		<small class="pull-right">
			Los Angeles City
		</small>
	</div>
</div>

app/views/pages/index.html.erb
<section id="hottest-tourney" class="no-padding">
	<div class="wrapper">
			<div class="container">
				<h1>Hottest Tournaments</h1>
				<div class="tourn-list row">
					<div class="col-sm-2">
						3 days ago
					</div>
					<div class="col-sm-7" align="left">
						<span>
							<%= image_tag('rails.png',:width=> "50px", :height=>"50px") %>
						</span>
						<span>
							<strong>
								Need 1v1 Age of Empires, Casual Game
							</strong>
						</span>
					</div>
					<div class="col-sm-3">
						Baguio City
					</div>
				</div>

				<div class="tourn-list row">
					<div class="col-sm-2">
						3 days ago
					</div>
					<div class="col-sm-7" align="left">
						<span>
							<%= image_tag('rails.png',:width=> "50px", :height=>"50px") %>
						</span>
						<span>
							<strong>
								Friday Night Magic
							</strong>
						</span>
					</div>
					<div class="col-sm-3">
						Cavite
					</div>
				</div>

				<div class="tourn-list row">
					<div class="col-sm-2">
						3 days ago
					</div>
					<div class="col-sm-7" align="left">
						<span>
							<%= image_tag('rails.png',:width=> "50px", :height=>"50px") %>
						</span>
						<span>
							<strong>
								Inter-Barangay sa Pasig
							</strong>
						</span>
					</div>
					<div class="col-sm-3">
						pasig City
					</div>
				</div>

			</div>
	</div>
</section>

<div class="wrapper">
	<div class="container">
		<h1 align="center">Newest Tourneys</h1>
		<div class="row">
			<div class="col-md-6">
				<h3>Casuals</h3>
				<%= render partial: "newest_tourney_casuals", :collection => @newest_casuals %>
			</div>
			<div class="col-md-6">
				<h3>Tournaments</h3>
				<%= render partial: "newest_tourney_tournaments", :collection => @newest_tournaments %>
			</div>
		</div>
	</div>
</div>