config/routes.rb
BaseApp::Application.routes.draw do

  resources :messagers

  root :to => "pages#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
  										:registrations => "registrations" }


  get "pages/index"

  get "/admin" => "admin/base#index", :as => "admin"

  namespace "admin" do

    resources :users

  end

  resources :tourneys
  resources :tourney_comments

  match 'users/dashboard', :to => 'user#index', :via => [:get], :as => :my_dashboard
  match 'users/:id', :to => 'user#members_dashboard', :via => [:get], :as => :users_dashboard

  match '/tourneys/:id/rsvp', :to => 'tourneys#rsvp', :via => [:post], :as => :tourneys_rsvp
end

app/models/board.rb
class Board < ActiveRecord::Base
end

app/models/cards.rb
class Cards < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :game_type
end

app/models/game_mode.rb
class GameMode < ActiveRecord::Base
end

app/models/game_type.rb
class GameType < ActiveRecord::Base
end

app/models/games.rb
class Games < ActiveRecord::Base
  belongs_to :game_type
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  belongs_to :tourney
end

app/models/join_tourney.rb
class JoinTourney < ActiveRecord::Base
  belongs_to :user
  belongs_to :tourney
end

app/models/messager.rb
class Messager < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base

  has_and_belongs_to_many :users

  def self.admin
    find_or_create_by(:name => "admin")
  end

end

app/models/rsvp_stats.rb
class RsvpStats < ActiveRecord::Base
  belongs_to :users
  belongs_to :tourneys
end

app/models/schedules.rb
class Schedules < ActiveRecord::Base
end

app/models/sports.rb
class Sports < ActiveRecord::Base
end

app/models/tourney.rb
class Tourney < ActiveRecord::Base
  belongs_to :tourney_type
  belongs_to :tourney_comment
  belongs_to :tourney_comments
  belongs_to :user
  belongs_to :venue
  belongs_to :game_type
end

app/models/tourney_comment.rb
class TourneyComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :tourney
end

app/models/tourney_type.rb
class TourneyType < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable

  has_and_belongs_to_many :roles
  belongs_to :tourney

  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end

  def make_admin
    self.roles << Role.admin
  end

  def revoke_admin
    self.roles.delete(Role.admin)
  end

  def admin?
    role?(:admin)
  end

  attr_accessor :login, :new_user

  def password_salt
    "no salt"
  end

  def password_salt=(salt)
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def new_user=(new_user)
    @new_user = new_user
  end

  def new_user
    @new_user
  end

  # new function to set the password without knowing the current password used in our confirmation controller.
  def attempt_set_password(params)
    update_attributes(params)
  end
  # new function to return whether a password has been set
  def has_no_password?
    self.encrypted_password.blank?
  end

  # new function to provide access to protected method unless_confirmed
  def only_if_unconfirmed
    pending_any_confirmation {yield}
  end

  # Password is required if it is being set, but not for new records
  def password_required?
    if !persisted?
      false
    else
      !password.nil? || !password_confirmation.nil?
    end
  end

  def password_match?
    self.errors[:password] << "can't be blank" if password.blank?
    self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    self.errors[:password_confirmation] << "does not match password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token['info']
    if user = User.find_by_email(data["email"])
      user
    else # Create a user with a stub password.
      User.create!(:email => data["email"], :password => Devise.friendly_token[0,20])
    end
  end

end

app/models/venues.rb
class Venues < ActiveRecord::Base
end

app/models/video_game.rb
class VideoGame < ActiveRecord::Base
end

app/models/video_games.rb
class VideoGames < ActiveRecord::Base
end

app/controllers/tourney_comments_controller.rb
class TourneyCommentsController < ApplicationController
  before_action :set_tourney_comment, only: [:show, :edit, :update, :destroy]

  # GET /tourney_comments
  def index
    @tourney_comments = TourneyComment.all
  end

  # GET /tourney_comments/1
  def show
  end

  # GET /tourney_comments/new
  def new
    @tourney_comment = TourneyComment.new
  end

  # GET /tourney_comments/1/edit
  def edit
  end

  # POST /tourney_comments
  def create
    @tourney_comment = TourneyComment.new(tourney_comment_params)

    if @tourney_comment.save
      redirect_to @tourney_comment, notice: 'Tourney comment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tourney_comments/1
  def update
    if @tourney_comment.update(tourney_comment_params)
      redirect_to @tourney_comment, notice: 'Tourney comment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tourney_comments/1
  def destroy
    @tourney_comment.destroy
    redirect_to tourney_comments_url, notice: 'Tourney comment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tourney_comment
      @tourney_comment = TourneyComment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tourney_comment_params
      params.require(:tourney_comment).permit(:tourney_id, :message, :user_id)
    end
end

app/helpers/tourney_comments_helper.rb
module TourneyCommentsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/tourney_comments/_form.html.erb
<%= form_for(@tourney_comment) do |f| %>
  <% if @tourney_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tourney_comment.errors.count, "error") %> prohibited this tourney_comment from being saved:</h2>

      <ul>
      <% @tourney_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tourney_comments/edit.html.erb
<h1>Editing tourney_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @tourney_comment %> |
<%= link_to 'Back', tourney_comments_path %>

app/views/tourney_comments/index.html.erb
<h1>Listing tourney_comments</h1>

<table>
  <thead>
    <tr>
      <th>Tourney</th>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <%= debug @tourney_comment %>
    <% @tourney_comments.each do |tourney_comment| %>
      <tr>
        <td><%= tourney_comment.tourney.title %></td>
        <td><%= tourney_comment.message %></td>
        <td><%= tourney_comment.user.email %></td>
        <td><%= link_to 'Show', tourney_comment %></td>
        <td><%= link_to 'Edit', edit_tourney_comment_path(tourney_comment) %></td>
        <td><%= link_to 'Destroy', tourney_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tourney comment', new_tourney_comment_path %>

app/views/tourney_comments/new.html.erb
<h1>New tourney_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', tourney_comments_path %>

app/views/tourney_comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tourney_comment_path(@tourney_comment) %> |
<%= link_to 'Back', tourney_comments_path %>