config/routes.rb
BaseApp::Application.routes.draw do

  resources :messagers

  root :to => "pages#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
  										:registrations => "registrations" }


  get "pages/index"

  get "/admin" => "admin/base#index", :as => "admin"

  namespace "admin" do

    resources :users

  end

  resources :tourneys
  resources :tourney_comments

  match 'users/dashboard', :to => 'user#index', :via => [:get], :as => :my_dashboard
  match 'users/:id', :to => 'user#members_dashboard', :via => [:get], :as => :users_dashboard

  match '/tourneys/:id/rsvp', :to => 'tourneys#rsvp', :via => [:post], :as => :tourneys_rsvp
end

app/models/board.rb
class Board < ActiveRecord::Base
end

app/models/cards.rb
class Cards < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :game_type
end

app/models/game_mode.rb
class GameMode < ActiveRecord::Base
end

app/models/game_type.rb
class GameType < ActiveRecord::Base
end

app/models/games.rb
class Games < ActiveRecord::Base
  belongs_to :game_type
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  belongs_to :tourney
end

app/models/join_tourney.rb
class JoinTourney < ActiveRecord::Base
  belongs_to :user
  belongs_to :tourney
end

app/models/messager.rb
class Messager < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base

  has_and_belongs_to_many :users

  def self.admin
    find_or_create_by(:name => "admin")
  end

end

app/models/rsvp_stats.rb
class RsvpStats < ActiveRecord::Base
  belongs_to :users
  belongs_to :tourneys
end

app/models/schedules.rb
class Schedules < ActiveRecord::Base
end

app/models/sports.rb
class Sports < ActiveRecord::Base
end

app/models/tourney.rb
class Tourney < ActiveRecord::Base
  belongs_to :tourney_type
  belongs_to :tourney_comment
  belongs_to :tourney_comments
  belongs_to :user
  belongs_to :venue
  belongs_to :game_type
end

app/models/tourney_type.rb
class TourneyType < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable

  has_and_belongs_to_many :roles
  belongs_to :tourney

  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end

  def make_admin
    self.roles << Role.admin
  end

  def revoke_admin
    self.roles.delete(Role.admin)
  end

  def admin?
    role?(:admin)
  end

  attr_accessor :login, :new_user

  def password_salt
    "no salt"
  end

  def password_salt=(salt)
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def new_user=(new_user)
    @new_user = new_user
  end

  def new_user
    @new_user
  end

  # new function to set the password without knowing the current password used in our confirmation controller.
  def attempt_set_password(params)
    update_attributes(params)
  end
  # new function to return whether a password has been set
  def has_no_password?
    self.encrypted_password.blank?
  end

  # new function to provide access to protected method unless_confirmed
  def only_if_unconfirmed
    pending_any_confirmation {yield}
  end

  # Password is required if it is being set, but not for new records
  def password_required?
    if !persisted?
      false
    else
      !password.nil? || !password_confirmation.nil?
    end
  end

  def password_match?
    self.errors[:password] << "can't be blank" if password.blank?
    self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    self.errors[:password_confirmation] << "does not match password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token['info']
    if user = User.find_by_email(data["email"])
      user
    else # Create a user with a stub password.
      User.create!(:email => data["email"], :password => Devise.friendly_token[0,20])
    end
  end

end

app/models/venues.rb
class Venues < ActiveRecord::Base
end

app/models/video_game.rb
class VideoGame < ActiveRecord::Base
end

app/models/video_games.rb
class VideoGames < ActiveRecord::Base
end

app/controllers/messagers_controller.rb
class MessagersController < ApplicationController
  before_action :set_messager, only: [:show, :edit, :update, :destroy]

  # GET /messagers
  def index
    @messagers = Messager.all
  end

  # GET /messagers/1
  def show
  end

  # GET /messagers/new
  def new
    @messager = Messager.new
  end

  # GET /messagers/1/edit
  def edit
  end

  # POST /messagers
  def create
    @messager = Messager.new(messager_params)

    @message_type = Messager.message_type("SEND")
    @mobile_number = Messager.User.find(id).contact
    @sc = Messager.create { short("292908769")
    @m_id = Messager.message_id("12345678123456781234567812345678")
    @message = Messager.message
    @c_id = Messager.client_id("20979ad86da809c5aec43d96d18d603b7f75248d7bf57ae67101c972f57c8e02")
    @secret_key = Messager.secret_key("b08d0de99c40099bba90a1673eb6bb7557d078dd57f4be19616dfd3f8920e374")

    if @messager.save
      redirect_to @messager, notice: 'Messager was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /messagers/1
  def update
    if @messager.update(messager_params)
      redirect_to @messager, notice: 'Messager was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /messagers/1
  def destroy
    @messager.destroy
    redirect_to messagers_url, notice: 'Messager was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_messager
      @messager = Messager.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def messager_params
      params.require(:messager).permit(:message_type, :user_id, :shortcode, :message_id, :message, :client_id, :secret_key)
    end
end

app/helpers/messagers_helper.rb
module MessagersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/messagers/_form.html.erb
<%= form_for(@messager) do |f| %>
  <% if @messager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@messager.errors.count, "error") %> prohibited this messager from being saved:</h2>

      <ul>
      <% @messager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message_type %><br>
    <%= f.text_field :message_type %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :shortcode %><br>
    <%= f.text_field :shortcode %>
  </div>
  <div class="field">
    <%= f.label :message_id %><br>
    <%= f.text_field :message_id %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.text_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :secret_key %><br>
    <%= f.text_field :secret_key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messagers/edit.html.erb
<h1>Editing messager</h1>

<%= render 'form' %>

<%= link_to 'Show', @messager %> |
<%= link_to 'Back', messagers_path %>

app/views/messagers/index.html.erb
<h1>Listing messagers</h1>

<table>
  <thead>
    <tr>
      <th>Message type</th>
      <th>User</th>
      <th>Shortcode</th>
      <th>Message</th>
      <th>Message</th>
      <th>Client</th>
      <th>Secret key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messagers.each do |messager| %>
      <tr>
        <td><%= messager.message_type %></td>
        <td><%= messager.user %></td>
        <td><%= messager.shortcode %></td>
        <td><%= messager.message_id %></td>
        <td><%= messager.message %></td>
        <td><%= messager.client_id %></td>
        <td><%= messager.secret_key %></td>
        <td><%= link_to 'Show', messager %></td>
        <td><%= link_to 'Edit', edit_messager_path(messager) %></td>
        <td><%= link_to 'Destroy', messager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Messager', new_messager_path %>

app/views/messagers/new.html.erb
<h1>New messager</h1>

<%= render 'form' %>

<%= link_to 'Back', messagers_path %>

app/views/messagers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message type:</strong>
  <%= @messager.message_type %>
</p>

<p>
  <strong>User:</strong>
  <%= @messager.user %>
</p>

<p>
  <strong>Shortcode:</strong>
  <%= @messager.shortcode %>
</p>

<p>
  <strong>Message:</strong>
  <%= @messager.message_id %>
</p>

<p>
  <strong>Message:</strong>
  <%= @messager.message %>
</p>

<p>
  <strong>Client:</strong>
  <%= @messager.client_id %>
</p>

<p>
  <strong>Secret key:</strong>
  <%= @messager.secret_key %>
</p>

<%= link_to 'Edit', edit_messager_path(@messager) %> |
<%= link_to 'Back', messagers_path %>